name: Run main.py

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
  
      - name: Install dependencies
        run: pip install -r requirements.txt

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Code (Black)
        run: pip install black && black --check .

      - name: Run Linting (Flake8)
        run: pip install flake8 && flake8 --max-line-length=127 --exclude tests,.venv,venv . 

      - name: Run Import Sorting (isort)
        run: pip install isort && isort --check-only --skip tests .

  Security_scan:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Apprentice Management System"
          path: "."
          format: "HTML"
        continue-on-error: true

      - name: Run Security Scan (Bandit)
        run: pip install bandit &&  bandit -r . --severity-level high
    
      - name: Check Dependency Security (Safety)
        run: pip install safety && safety check

  SAST_analysis:
    needs: setup
    runs-on: ubuntu-latest
    steps:    
      - name: Run SAST Analysis (Semgrep)
        run: pip install semgrep && semgrep scan --config=python

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest --disable-warnings
        working-directory: ./tests 


        